import 'package:api_implementation/Model%20Classes/Engadget/Content.dart';
import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

// simple data provider class
class DataProvider {
  static final _news = Dio();
  static Future<AutoGenerated> getNews(String newsLink) async {
    try {
      final rawData = await _news.get(newsLink);
      print(rawData);
      final AutoGenerated dataa =
          AutoGenerated.fromJson(rawData.data as Map<String, dynamic>);
      return dataa;
    } catch (e) {
      rethrow;
    }
  }
}

// news prodiver class using provider package
class NewsProvider with ChangeNotifier {
  final Dio _news = Dio();
  AutoGenerated? _currentNews; // Stores the currently loaded news

  Future<void> fetchNews(String newsLink) async {
    try {
      final rawData = await _news.get(newsLink);
      _currentNews =
          AutoGenerated.fromJson(rawData.data as Map<String, dynamic>);
      notifyListeners();
    } catch (e) {
      throw e;
    }
  }

  AutoGenerated? get currentNews => _currentNews;
}
